"""Generate the 10-word teaching matrix and reproducible two-dimensional GloVe fit.
Run from any directory with Python 3; no external packages are required.
"""
import json
import math
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parent
WORDS = ['coffee', 'tea', 'milk', 'juice', 'cup', 'drink', 'hot', 'cold', 'car', 'road']
# Invented corpus: each edge represents this many copies of a two-token sentence.
# Symmetric radius-one windows give the two corresponding matrix entries.
EDGES = [
    ('coffee', 'tea', 2), ('coffee', 'milk', 3),
    ('coffee', 'cup', 12), ('tea', 'cup', 10), ('milk', 'cup', 4), ('juice', 'cup', 2),
    ('coffee', 'drink', 16), ('tea', 'drink', 14), ('milk', 'drink', 8), ('juice', 'drink', 10),
    ('coffee', 'hot', 14), ('tea', 'hot', 12), ('milk', 'hot', 3), ('juice', 'hot', 1),
    ('coffee', 'cold', 3), ('tea', 'cold', 2), ('milk', 'cold', 6), ('juice', 'cold', 12),
    ('car', 'road', 18),
]


def build():
    rng = random.Random(351)
    matrix = [[0] * len(WORDS) for _ in WORDS]
    for a, b, count in EDGES:
        i, j = WORDS.index(a), WORDS.index(b)
        matrix[i][j] = matrix[j][i] = count
    w = [[rng.uniform(-.1, .1) for _ in range(2)] for _ in WORDS]
    u = [[rng.uniform(-.1, .1) for _ in range(2)] for _ in WORDS]
    b, c = [0.] * 10, [0.] * 10
    aw, au = [[1.] * 2 for _ in WORDS], [[1.] * 2 for _ in WORDS]
    ab, ac = [1.] * 10, [1.] * 10
    cells = [(i, j, x) for i, row in enumerate(matrix) for j, x in enumerate(row) if x]
    weight = lambda x: min((x / 10.) ** .75, 1.)

    def score(i, j):
        return sum(a * z for a, z in zip(w[i], u[j])) + b[i] + c[j]

    def snapshot(epoch):
        return dict(epoch=epoch, word_vectors=[v[:] for v in w], context_vectors=[v[:] for v in u],
                    word_biases=b[:], context_biases=c[:],
                    predicted_log_counts=[[score(i, j) for j in range(10)] for i in range(10)],
                    mean_weighted_error=sum(weight(x) * (score(i, j) - math.log(x)) ** 2 for i, j, x in cells) / len(cells))

    initial = snapshot(0)
    for epoch in range(1, 401):
        rng.shuffle(cells)
        for i, j, x in cells:
            gradient = 2 * weight(x) * (score(i, j) - math.log(x))
            old_w = w[i][:]
            for d in range(2):
                gw, gu = gradient * u[j][d], gradient * old_w[d]
                aw[i][d] += gw * gw
                au[j][d] += gu * gu
                w[i][d] -= .08 * gw / math.sqrt(aw[i][d])
                u[j][d] -= .08 * gu / math.sqrt(au[j][d])
            ab[i] += gradient * gradient
            ac[j] += gradient * gradient
            b[i] -= .08 * gradient / math.sqrt(ab[i])
            c[j] -= .08 * gradient / math.sqrt(ac[j])
    final = snapshot(400)
    return dict(words=WORDS, matrix=matrix, corpus_edges=EDGES, initial=initial, final=final,
                settings=dict(seed=351, dimensions=2, epochs=400, optimizer='AdaGrad', learning_rate=.08, xmax=10, alpha=.75))


def render(data):
    matrix = data['matrix']
    cup = WORDS.index('cup')
    cells = ['<table class="glove-ten-matrix" aria-label="Ten-word symmetric co-occurrence matrix; cup column highlighted"><thead><tr><th>word</th>']
    cells.extend(f'<th class="{"cup-column" if j == cup else ""}">{word}</th>' for j, word in enumerate(WORDS))
    cells.append('</tr></thead><tbody>')
    for i, word in enumerate(WORDS):
        cells.append(f'<tr><th scope="row">{word}</th>')
        for j, value in enumerate(matrix[i]):
            cls = 'cup-column' if j == cup else 'matrix-zero' if not value else ''
            cells.append(f'<td class="{cls}">{value}</td>')
        cells.append('</tr>')
    cells.append('</tbody></table>')
    total = sum(row[cup] for row in matrix)
    ranking = sorted((i for i in range(10) if i != cup), key=lambda i: -matrix[i][cup])
    ranked = '\n'.join(f'| **{WORDS[i]}** | {matrix[i][cup]} | {matrix[i][cup] / total:.3f} |' for i in ranking)
    initial, final = data['initial'], data['final']
    vector = lambda v: '[' + ', '.join(f'{x:.3f}' for x in v) + ']'
    comparisons = '\n'.join(f'| {WORDS[i]} → cup | {matrix[i][cup]} | {math.log(matrix[i][cup]):.3f} | {initial["predicted_log_counts"][i][cup]:.3f} | **{final["predicted_log_counts"][i][cup]:.3f}** |' for i in range(4))
    return f'''<!-- Generated by build_glove_example.py; edit the generator to change these slides. -->
## Ten words: which one belongs beside “cup”? {{#glove-ten-words .glove-example}}

{''.join(cells)}

<div class="glove-lookup-pause"><b>PAUSE</b><span>Context = <strong>cup</strong>. Read the highlighted column. Which candidate has the largest count?</span></div>

::: {{.notes}}
Invented teaching corpus: each nonzero unordered pair corresponds to the stated number of copies of a two-token sentence. Count both directions in a radius-one window; do not cross sentence boundaries. The full 10 × 10 matrix is symmetric. This is an association lookup, not next-word prediction. Do not reveal the answer until the following slide.
:::

## The column gives the answer {{#glove-cup-ranking .glove-example}}

| Candidate | Count beside cup | Count / {total} |
|---|---:|---:|
{ranked}

<div class="glove-example-caption"><strong>Coffee wins:</strong> 12 of {total} observed neighbors. This answer comes directly from the counts.</div>

::: {{.notes}}
The final column is the empirical probability of a candidate token among this corpus's cup neighbors. The diagonal is zero because the corpus contains no repeated-token sentences. The five zero-count candidates tie; their order is arbitrary. These are unordered context associations and do not model sentence order.
:::

## Can short vectors reproduce those counts? {{#glove-reconstruct-question .glove-example}}

<div class="glove-reconstruct-target">Observed: <strong>coffee → cup = 12</strong></div>

| Learned parameter | Two coordinates | Bias |
|---|---|---:|
| coffee · word vector | `{vector(final['word_vectors'][0])}` | {final['word_biases'][0]:.3f} |
| cup · context vector | `{vector(final['context_vectors'][cup])}` | {final['context_biases'][cup]:.3f} |

$$\\widehat{{\\ell}}_{{coffee,cup}}=\\mathbf w_{{coffee}}^T\\widetilde{{\\mathbf w}}_{{cup}}+b_{{coffee}}+\\widetilde b_{{cup}}$$

<div class="glove-lookup-pause"><b>PAUSE</b><span>Multiply matching coordinates, add them, then add both biases. How close is the result to <strong>ln 12 ≈ 2.485</strong>?</span></div>

::: {{.notes}}
These are actual fitted parameters from a seeded two-dimensional GloVe model, not hand-picked coordinates. Both vector tables and bias tables were fitted against all nonzero cells in this exact matrix. The two-dimensional bottleneck shares parameters across cells. Training settings: seed 351; 400 AdaGrad epochs; learning rate 0.08; f(x) = min((x/10)^0.75, 1). Ten is a teaching setting for the weighting cap. Show the worked score on the next slide. Displayed parameters are rounded to three decimals.
:::

## Compare the predictions with the same data {{#glove-reconstruction .glove-example}}

| Pair | Count | Target: ln count | Before training | After training |
|---|---:|---:|---:|---:|
{comparisons}

<div class="glove-fit-score">coffee · cup + both biases ≈ <strong>{final['predicted_log_counts'][0][cup]:.3f}</strong><span>Target: 2.485</span></div>
<div class="glove-example-caption">Mean weighted squared error over all nonzero cells: <strong>{initial['mean_weighted_error']:.3f} → {final['mean_weighted_error']:.4f}</strong></div>
<div class="glove-example-question">What objective makes these predictions approach the log counts?</div>

::: {{.notes}}
The before/after entries are genuine outputs of the same model and matrix, at initialization and after training. The dot product plus biases predicts a log count, not a word probability. Zero cells are omitted from the GloVe loss, so they are not trained negative examples. Do not infer that zero-count pairs must receive low model scores. The loss is averaged over all positive directed cells, not just the four rows displayed here. Full values and settings are in glove-example-data.json; regenerate both the data and these slides with build_glove_example.py.
:::

'''


if __name__ == '__main__':
    data = build()
    (ROOT / 'glove-example-data.json').write_text(json.dumps(data, indent=2) + '\n')
    (ROOT / '_glove-example.md').write_text(render(data))
    print('Mean weighted error:', data['initial']['mean_weighted_error'], '→', data['final']['mean_weighted_error'])
    print('Cup predictions:', [round(row[4], 4) for row in data['final']['predicted_log_counts'][:4]])
